import Head from "next/head";
import styles from "../styles/Home.module.css";
import Sidebar from "../src/components/Sidebar";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar />
        <h1>Front de componente</h1>
      </main>
    </>
  );
}
